In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def NFLdataframe(): 
    cities.rename(columns = {'Population (2016 est.)[8]':'Population'}, inplace =True)
    pop = cities[['Metropolitan area','Population','NFL']]
    pop['NFL'].replace('—',np.nan,inplace=True)
    pop['NFL']=cities['NFL'].str.extract(pat = '(^[\w\. ]+)', expand=False)
    pop['Population']=pop['Population'].apply(pd.to_numeric,errors= 'coerce')
    pop.dropna(inplace=True)
    pop.set_index('Metropolitan area',inplace=True)

    NFLdata = nfl_df[nfl_df['year']==2018]
    NFL =NFLdata[['W','L','W-L%']].apply(pd.to_numeric,errors= 'coerce').dropna()
    NFL['team'] = NFLdata['team'].str.extract('(^[\w\. ]+)',expand =False).str.strip()

    NYW = NFL[NFL['team'] == 'New York Jets']['W'].values[0]+ NFL[NFL['team'] == 'New York Giants']['W'].values[0] 
    NYL = NFL[NFL['team'] == 'New York Jets']['L'].values[0]+ NFL[NFL['team'] == 'New York Giants']['L'].values[0]
    LAL = NFL[NFL['team'] == 'Los Angeles Rams']['L'].values[0]+ NFL[NFL['team'] == 'Los Angeles Chargers']['L'].values[0]
    LAW = NFL[NFL['team'] == 'Los Angeles Rams']['W'].values[0]+ NFL[NFL['team'] == 'Los Angeles Chargers']['W'].values[0]
    SFW = NFL[NFL['team'] == 'Oakland Raiders']['W'].values[0]+ NFL[NFL['team'] == 'San Francisco 49ers']['W'].values[0] 
    SFL = NFL[NFL['team'] == 'Oakland Raiders']['L'].values[0]+ NFL[NFL['team'] == 'San Francisco 49ers']['L'].values[0]

    NYR = NYW/(NYW+NYL)
    LAR = LAW/(LAW+LAL)
    SFR = SFW/(SFW+SFL)

    refusion = Mend= [{'team' : 'Giants Jets','W' : NYW , 'L' : NYL, 'W-L%': NYR},
                      {'team' : 'Rams Chargers','W' : LAW , 'L' : LAL, 'W-L%': LAR},
                      {'team': '49ers Raiders','W': SFW, 'L': SFL, 'W-L%': SFR}]
    NFL = NFL.append(refusion, ignore_index= True).drop([3,13,15,19,28,30])

    teamlst =[]
    for cityteam in pop['NFL']:
        popteam = NFL[NFL['team'].str.contains(cityteam, na =False)]['team'].values[0]
        teamlst.append({'Metropolitan area': pop.loc[pop['NFL'] == cityteam].index[0], 'team': popteam})
    teamdata = pd.DataFrame(teamlst)
    teamdata = teamdata.merge(pop, how ='outer',on ='Metropolitan area')
    teamdata = teamdata.merge(NFL, how ='left', on ='team')
    return teamdata

In [3]:
mlb_df=pd.read_csv("assets/mlb.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def MLBdataframe(): 
    mlb_df=pd.read_csv("assets/mlb.csv")
    cities=pd.read_html("assets/wikipedia_data.html")[1]
    cities=cities.iloc[:-1,[0,3,5,6,7,8]]

    cities.rename(columns = {'Population (2016 est.)[8]':'Population'}, inplace =True)
    pop = cities[['Metropolitan area','Population','MLB']]
    pop['MLB'].replace('—',np.nan,inplace=True)
    pop['MLB']=cities['MLB'].str.extract(pat = '(^[\w\. ]+)', expand=False)
    pop['Population']=pop['Population'].apply(pd.to_numeric,errors= 'coerce')
    pop.dropna(inplace=True)
    pop.set_index('Metropolitan area',inplace=True)

    MLBdata = mlb_df[mlb_df['year']==2018]
    MLB =MLBdata[['W','L','W-L%']].apply(pd.to_numeric,errors= 'coerce').dropna()
    MLB['team'] = MLBdata['team'].str.extract('(^[\w\. ]+)',expand =False).str.strip()

    NYW = MLB[MLB['team'] == 'New York Mets']['W'].values[0]+ MLB[MLB['team'] == 'New York Yankees']['W'].values[0] 
    NYL = MLB[MLB['team'] == 'New York Mets']['L'].values[0]+ MLB[MLB['team'] == 'New York Yankees']['L'].values[0]
    LAL = MLB[MLB['team'] == 'Los Angeles Angels']['L'].values[0]+ MLB[MLB['team'] == 'Los Angeles Dodgers']['L'].values[0]
    LAW = MLB[MLB['team'] == 'Los Angeles Angels']['W'].values[0]+ MLB[MLB['team'] == 'Los Angeles Dodgers']['W'].values[0]
    SFW = MLB[MLB['team'] == 'Oakland Athletics']['W'].values[0]+ MLB[MLB['team'] == 'San Francisco Giants']['W'].values[0] 
    SFL = MLB[MLB['team'] == 'Oakland Athletics']['L'].values[0]+ MLB[MLB['team'] == 'San Francisco Giants']['L'].values[0]
    CHW = MLB[MLB['team'] == 'Chicago White Sox']['W'].values[0]+ MLB[MLB['team'] == 'Chicago Cubs']['W'].values[0]
    CHL = MLB[MLB['team'] == 'Chicago White Sox']['L'].values[0]+ MLB[MLB['team'] == 'Chicago Cubs']['L'].values[0]
    NYR = NYW/(NYW+NYL)
    LAR = LAW/(LAW+LAL)
    SFR = SFW/(SFW+SFL)
    CHR = CHW/(CHW+CHL)
    Mend= [{'team' : 'Yankees Mets','W' : NYW , 'L' : NYL, 'W-L%': NYR},
          {'team' : 'Dodgers Angels','W' : LAW , 'L' : LAL, 'W-L%': LAR},
          {'team': 'Giants Athletics','W': SFW, 'L': SFL, 'W-L%': SFR},
          {'team': 'Cubs White Sox','W': CHW, 'L': CHL, 'W-L%': CHR}]
    MLB = MLB.append(Mend, ignore_index = True).drop([1,8,11,13,18,21,25,28])
    teamlst =[]
    for cityteam in pop['MLB']:
        popteam = MLB[MLB['team'].str.contains(cityteam, na =False)]['team'].values[0]
        teamlst.append({'Metropolitan area': pop.loc[pop['MLB'] == cityteam].index[0], 'team': popteam})
    teamdata = pd.DataFrame(teamlst)
    teamdata = teamdata.merge(pop, how ='outer',on ='Metropolitan area')
    teamdata = teamdata.merge(MLB, how ='left', on ='team')
    return teamdata

In [4]:
nba_df=pd.read_csv("assets/nba.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def NBAdataframe():
    cities.rename(columns = {'Population (2016 est.)[8]':'Population'}, inplace =True)
    pop = cities[['Metropolitan area','Population','NBA']]
    pop['NBA'].replace('—',np.nan,inplace=True)
    pop['NBA']=cities['NBA'].str.extract(pat = '(^[\w ]+)', expand=False)
    pop['Population']=pop['Population'].apply(pd.to_numeric,errors= 'coerce')
    pop.dropna(inplace=True)
    pop.set_index('Metropolitan area',inplace=True)
    
    NBAdata = nba_df[nba_df['year']==2018]
    NBA =NBAdata[['W','L','W/L%']].apply(pd.to_numeric,errors= 'coerce').dropna()
    NBA['team']= NBAdata['team'].str.extract('(^[\w ]+)',expand =False).str.strip()
    
    NYW = NBA[NBA['team'] == 'New York Knicks']['W'].values[0]+ NBA[NBA['team'] == 'Brooklyn Nets']['W'].values[0] 
    NYL = NBA[NBA['team'] == 'New York Knicks']['L'].values[0]+ NBA[NBA['team'] == 'Brooklyn Nets']['L'].values[0]
    LAL = NBA[NBA['team'] == 'Los Angeles Clippers']['L'].values[0]+ NBA[NBA['team'] == 'Los Angeles Lakers']['L'].values[0]
    LAW = NBA[NBA['team'] == 'Los Angeles Clippers']['W'].values[0]+ NBA[NBA['team'] == 'Los Angeles Lakers']['W'].values[0]
    NYR = NYW/(NYW+NYL)
    LAR = LAW/(LAW+LAL)

    Addons= [{'team' : 'Knicks Nets','W' :NYW ,'L' : NYL,'W/L%': NYR},
         {'team' : 'Lakers Clippers','W' : LAW ,'L' : LAL,'W/L%': LAR}]
    NBA = NBA.append(Addons, ignore_index =True).drop([10,11,25,24])
    
    teamlst =[]
    for cityteam in pop['NBA']:
        popteam = NBA[NBA['team'].str.contains(cityteam, na =False)]['team'].values[0]
        teamlst.append({'Metropolitan area': pop.loc[pop['NBA'] == cityteam].index[0], 'team': popteam})
    teamdata = pd.DataFrame(teamlst)
    teamdata = teamdata.merge(pop, how ='outer',on ='Metropolitan area')
    teamdata = teamdata.merge(NBA, how ='left', on ='team')    
    return teamdata

In [5]:
nhl_df=pd.read_csv("assets/nhl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def NHLdataframe(): 
    # qurey data since 2018, covert column type to int
    NHLdata = nhl_df[nhl_df['year']==2018]
    NHL =NHLdata[['W','L']].apply(pd.to_numeric,errors= 'coerce').dropna()
    NHL['team']= NHLdata['team']
    NHL['team'] = NHL['team'].str.extract('([^\d\(\)\*]+)', expand=False).str.strip()
    #Clean up population dataframe
    cities.rename(columns = {'Population (2016 est.)[8]':'Population'}, inplace =True)
    pop = cities[['Metropolitan area','Population','NHL']]
    pop['NHL'].replace('—',np.nan,inplace=True)
    pop['NHL']=cities['NHL'].str.extract(pat = '(^[\w ]+)', expand=False).str.strip()
    pop['Population']=pop['Population'].apply(pd.to_numeric,errors= 'coerce')
    pop.dropna(inplace=True)
    pop.set_index('Metropolitan area', inplace =True)
    #win ratio column append
    NHL['win ratio'] = NHL['W']/(NHL['W']+NHL['L'])
    #Merge teams' win/lose value if they are in the same Metropolitian region
    NYW = NHL[NHL['team'] == 'New York Islanders']['W'].values[0]+ NHL[NHL['team'] == 'New York Rangers']['W'].values[0] + NHL[NHL['team']== 'New Jersey Devils']['W'].values[0]
    NYL = NHL[NHL['team'] == 'New York Islanders']['L'].values[0]+ NHL[NHL['team'] == 'New York Rangers']['L'].values[0] + NHL[NHL['team']== 'New Jersey Devils']['L'].values[0]
    LAL = NHL[NHL['team'] == 'Los Angeles Kings']['L'].values[0]+ NHL[NHL['team'] == 'Anaheim Ducks']['L'].values[0]
    LAW = NHL[NHL['team'] == 'Los Angeles Kings']['W'].values[0]+ NHL[NHL['team'] == 'Anaheim Ducks']['W'].values[0]
    NYR = NYW/(NYW+NYL)
    LAR = LAW/(LAW+LAL)
    addon = [{'team':'Rangers Islanders Devils', 'win ratio':NYR} ,{'team':'Kings Ducks','win ratio':LAR}]
    NHL = NHL.append(addon, ignore_index =True).drop([12,14,15,24,26])
    #iterate team from population and create a list of dictionaries with key:city name
    teamlst =[]
    for cityteam in pop['NHL']:
        popteam = NHL[NHL['team'].str.contains(pat = cityteam, na =False)]['team'].values[0]
        teamlst.append({'Metropolitan area': pop.loc[pop['NHL'] == cityteam].index[0], 'team': popteam})
        
    teamdata = pd.DataFrame(teamlst).merge(pop,how='left',on = 'Metropolitan area')
    teamdata=teamdata.merge(NHL, how = 'left', on = 'team')
    return teamdata

In [14]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
nhl_df=pd.read_csv("assets/nhl.csv")
nba_df=pd.read_csv("assets/nba.csv")
nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

mlbdata = MLBdataframe()
mlbdata = mlbdata[['Metropolitan area','W-L%']]
nhldata = NHLdataframe()
nhldata = nhldata[['Metropolitan area','win ratio']].rename(columns = {'win ratio':'W-L%'})
nbadata = NBAdataframe()
nbadata = nbadata[['Metropolitan area','W/L%']].rename(columns = {'W/L%':'W-L%'})
nfldata = NFLdataframe()
nfldata = nfldata[['Metropolitan area','W-L%']]
sports = ['NFL', 'NBA', 'NHL', 'MLB']
sports_df = {"NFL": nfldata, "NBA": nbadata, "NHL": nhldata, "MLB": mlbdata}

def sports_team_performance():   
    mlbdata = MLBdataframe()
    mlbdata = mlbdata[['Metropolitan area','W-L%']]
    nhldata = NHLdataframe()
    nhldata = nhldata[['Metropolitan area','win ratio']].rename(columns = {'win ratio':'W-L%'})
    nbadata = NBAdataframe()
    nbadata = nbadata[['Metropolitan area','W/L%']].rename(columns = {'W/L%':'W-L%'})
    nfldata = NFLdataframe()
    nfldata = nfldata[['Metropolitan area','W-L%']]
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    sports_df = {"NFL": nfldata, "NBA": nbadata, "NHL": nhldata, "MLB": mlbdata}

    def leaguePtest(league):    
        plst = []
        for i in sports:
            allian = pd.merge(sports_df[league], sports_df[i], on = 'Metropolitan area', how = 'inner')
            pvalue = stats.ttest_rel(allian["W-L%_x"], allian["W-L%_y"])[1]
            plst.append(pvalue)
        return plst              
    # Note: p_values is a full dataframe, so df.loc["NFL","NBA"] should be the same as df.loc["NBA","NFL"] and
    # df.loc["NFL","NFL"] should return np.nan
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({league:leaguePtest(league) for league in sports}, index=sports)
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values

         Metropolitan area      W-L%
0            New York City  0.546296
1              Los Angeles  0.529231
2   San Francisco Bay Area  0.524691
3                  Chicago  0.483077
4        Dallas–Fort Worth  0.414000
5         Washington, D.C.  0.506000
6             Philadelphia  0.494000
7                   Boston  0.667000
8   Minneapolis–Saint Paul  0.481000
9                   Denver  0.558000
10   Miami–Fort Lauderdale  0.391000
11                 Phoenix  0.506000
12                 Detroit  0.395000
13                 Toronto  0.451000
14                 Houston  0.636000
15                 Atlanta  0.556000
16          Tampa Bay Area  0.556000
17              Pittsburgh  0.509000
18               Cleveland  0.562000
19                 Seattle  0.549000
20              Cincinnati  0.414000
21             Kansas City  0.358000
22               St. Louis  0.543000
23               Baltimore  0.290000
24               Milwaukee  0.589000
25               San Diego  0.407000